# This file overrides https://github.com/bbatsov/rubocop/blob/master/config/default.yml

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Metrics/PerceivedComplexity:
  Max: 10

Metrics/CyclomaticComplexity:
  Max: 8

Metrics/AbcSize:
  Max: 20

Style/Documentation:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/Semicolon:
  Enabled: false

Lint/Eval:
  Enabled: false

Style/AccessorMethodName:
  Enabled: false

Style/DefWithParentheses:
  Enabled: false

Style/MethodCallParentheses:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Metrics/LineLength:
    Max: 100

Style/RedundantReturn:
  Enabled: false
