" Generated by vim-plug
" Sat Apr 10 18:49:27 2021
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['ale'].commit = '557a1ed5da70cb443a8650766f4e8ea95e8c0da3'
silent! let g:plugs['async.vim'].commit = '6102020b4690f05ab6509a37fa25bc53e2d799a9'
silent! let g:plugs['asyncomplete-around.vim'].commit = 'b74f0df33f3042c877e23d42ee6c507ac09bcc35'
silent! let g:plugs['asyncomplete-file.vim'].commit = 'af59997d19c8f5ee65b448249a9cddc51560e243'
silent! let g:plugs['asyncomplete-lsp.vim'].commit = '684c34453db9dcbed5dbf4769aaa6521530a23e0'
silent! let g:plugs['asyncomplete.vim'].commit = 'bb8a9924b703b3663d3be07d326055e44d22179a'
silent! let g:plugs['caw.vim'].commit = '26279f70cdfe5da2226cd15d7dd832ef6242ed26'
silent! let g:plugs['fern.vim'].commit = '2ac002dc2871098f46d22b861de786729a9bb394'
silent! let g:plugs['fzf'].commit = 'faf68dbc5cc52201d0962f73baa5a049528b913c'
silent! let g:plugs['fzf.vim'].commit = '01f7146cf6e903e31cd900944393bec86c6da4a6'
silent! let g:plugs['indentLine'].commit = '6107214eff0cac5d9810d29ae8614ddfdfcd986b'
silent! let g:plugs['lexima.vim'].commit = '89bf4dc13539131a29cf938074b3f1ce9d000bfd'
silent! let g:plugs['lightline-ale'].commit = '23352556fdaa067209fa22df424f1b88ab370f6a'
silent! let g:plugs['lightline.vim'].commit = 'ab2536a3779f7d1dc3011ad55990f2fd67b7d2d3'
silent! let g:plugs['vim-auto-save'].commit = '1685175183d160879ebcf231cd4c96b1b8a5a5c9'
silent! let g:plugs['vim-fugitive'].commit = '89e6b5e4e1d8152bfc3c26aa2655c0342d0809d1'
silent! let g:plugs['vim-gitgutter'].commit = 'ea79bc01c2efc84cf8e71fbe5fd8adbf4242739d'
silent! let g:plugs['vim-json'].commit = '3727f089410e23ae113be6222e8a08dd2613ecf2'
silent! let g:plugs['vim-lsp'].commit = 'd821bd8e189372ec394ea832cc214d8a82c40225'
silent! let g:plugs['vim-terraform'].commit = '6fd491d6a2ae40fef3aa6c414e096ce07664f030'
silent! let g:plugs['vim-vsnip'].commit = 'b08d78bb7df1f1d3b279dff182746e454b8080c5'
silent! let g:plugs['vim-vsnip-integ'].commit = '4a076bea73e307738ac5d08f60a0936cab391efd'

PlugUpdate!

