status:
	vim -c PlugStatus

install:
	vim -c PlugInstall

install-snapshot:
	vim -S ./snapshot.vim

update:
	vim -c PlugUpdate

clean:
	vim -c PlugClean

snapstop:
	vim -c "PlugSnapshot ./snapshot.vim"

