---
- name: Install anyenv
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
  with_items:
    - repo: "https://github.com/anyenv/anyenv"
      dest: "~/.anyenv"
    - repo: "https://github.com/znz/anyenv-update.git"
      dest: "~/.anyenv/plugins/anyenv-update"
    - repo: "https://github.com/znz/anyenv-git.git"
      dest: "~/.anyenv/plugins/anyenv-git"

- name: Update anyenv
  shell: |
    eval "$(anyenv init -)"
    anyenv update
  args:
    executable: /bin/bash

- name: Install envs
  shell: |
    eval "$(anyenv init -)"
    anyenv install --force-init
    anyenv install {{ item.env }}
    eval "$(anyenv init -)"
  args:
    executable: /bin/bash
    creates: ~/.anyenv/envs/{{ item.env }}
  with_items:
    - env: nodenv
    - env: goenv
    - env: pyenv
