- name: change mode for diff-highlight
  become: yes
  become_method: sudo
  file:
    path: '/usr/share/doc/git/contrib/diff-highlight/diff-highlight'
    mode: '755'

- name: Create symbolic link for diff-highlight
  become: yes
  become_method: sudo
  file:
    src: '/usr/share/doc/git/contrib/diff-highlight/diff-highlight'
    dest: '/usr/local/bin/diff-highlight'
    state: link

- name: Setup dotfiles
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  with_items:
    - src: '~/dotfiles/.gitconfig'
      dest: '~/.gitconfig'
    - src: '~/dotfiles/.gitignore'
      dest: '~/.gitignore'

- name: Add K8S GPG key
  become: yes
  become_method: sudo
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg

- name: Add K8S APT repository
  become: yes
  become_method: sudo
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main

- name: Add helm GPG key
  become: yes
  become_method: sudo
  apt_key:
    url: https://baltocdn.com/helm/signing.asc

- name: Add helm APT repository
  become: yes
  become_method: sudo
  apt_repository:
    repo: deb https://baltocdn.com/helm/stable/debian/ all main

- name: Install apt packages
  become: yes
  become_method: sudo
  apt:
    update_cache: yes
    cache_valid_time: 3600
    name:
      - curl
      - git
      - fzf
      - ripgrep
      - colordiff
      - source-highlight
      - jq
      - direnv
      - tree
      - python3-pip
      - python-is-python3
      - kubectl
      - helm

- name: Download jump command
  ansible.builtin.get_url:
    url: https://github.com/gsamokovarov/jump/releases/download/v0.50.0/jump_0.50.0_amd64.deb
    dest: /tmp

- name: Install jump command
  become: yes
  become_method: sudo
  ansible.builtin.apt:
    deb: /tmp/jump_0.50.0_amd64.deb
