run:
	ansible-playbook -i .inventory playbook.yaml

anyenv:
	ansible-playbook -i .inventory playbook.yaml -t anyenv

npm-install:
	ansible-playbook -i .inventory playbook.yaml -t node

vim-install:
	ansible-playbook -i .inventory playbook.yaml -t vim
