---
- name: Setup develop pc
  hosts: localhost
  connection: local
  become: 'no'
  tasks:
    - include: tasks/macos.yaml
      when: "ansible_os_family == 'Darwin'"
    - include: tasks/anyenv.yaml
      tags:
        - never
        - anyenv
    - include: tasks/vim.yaml
      tags:
        - never
        - vim

