---
- name: Setup develop pc
  hosts: localhost
  connection: local
  become: 'no'
  tasks:
    - import_tasks: tasks/macos.yaml
    - import_tasks: tasks/vim.yaml
      tags:
        - never
        - vim

