---
- name: Setup develop pc
  hosts: localhost
  connection: local
  become: 'no'
  tasks:
    - import_tasks: tasks/zsh.yaml
      vars:
        the_user: "{{ ansible_user_id }}"
    - import_tasks: tasks/debian.yaml
      when: "ansible_os_family == 'Debian'"
    - import_tasks: tasks/macos.yaml
      when: "ansible_os_family == 'Darwin'"
    - import_tasks: tasks/vim.yaml
      tags:
        - never
        - vim

