---
- name: Setup develop pc
  hosts: localhost
  connection: local
  become: 'no'
  tasks:
    - include: tasks/zsh.yaml
      vars:
        the_user: "{{ ansible_user_id }}"
    - include: tasks/debian.yaml
      when: "ansible_os_family == 'Debian'"
    - include: tasks/macos.yaml
      when: "ansible_os_family == 'Darwin'"
    - include_vars:
        file: vars/lang.yaml
        name: lang
      tags:
        - never
        - anyenv
    - include: tasks/anyenv.yaml
      tags:
        - never
        - anyenv
    - include: tasks/vim.yaml
      tags:
        - never
        - vim

