[[plugins]]
repo = 'Shougo/unite.vim'
hook_add = '''
nnoremap [unite]    <Nop>
nmap     <Space>u [unite]
nnoremap <silent> [unite]f   :<C-u>Unite file<CR>
nnoremap <silent> [unite]m   :<C-u>Unite file_mru<CR>
nnoremap <silent> [unite]b   :<C-u>Unite buffer<CR>
nnoremap <silent> [unite]r   :<C-u>Unite -buffer-name=register register<CR>
nnoremap <silent> [unite]k   :<C-u>Unite bookmark<CR>
nnoremap <silent> [unite]o   :<C-u>Unite outline<CR>
'''

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'Shougo/neomru.vim'
on_path = '.*'
hook_add = '''
let g:neomru#file_mru_limit = 10000
'''

[[plugins]]
repo = 'Shougo/neoyank.vim'
on_path = '.*'
hook_add = '''
let g:neoyank#limit = 10000
'''

# 非同期Syntastic
[[plugins]]
repo = 'neomake/neomake'
hook_add = '''
autocmd! BufWritePost * Neomake
'''
hook_source = '''
let g:neomake_error_sign = { 'texthl': 'NeomakeErrorMsg' }
'''

